---
title: 'ggplot2 Elegant Graphics: Chapter 4'
author: "Brandon Foltz"
date: "2023-03-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(nlme)
```

```{r}
#head(Oxboys)

ggplot(Oxboys, aes(age, height, group = Subject)) +
  geom_point() +
  geom_line()

# common mistake
ggplot(Oxboys, aes(age, height)) +
  geom_point() +
  geom_line()
```

Different groups on different layers

```{r}
ggplot(Oxboys, aes(age, height, group = Subject)) +
  geom_line() +
  geom_smooth(method = "lm", se = FALSE)

# place geom in the smooth to get ONE line for all subjects
ggplot(Oxboys, aes(age, height)) +
  geom_line(aes(group = Subject)) +
  geom_smooth(method = "lm", size = 2, se = FALSE)

Oxboys_model <- lm(Oxboys$height ~ Oxboys$age, Oxboys)
```
 
Overrriding the default grouping

```{r}
ggplot(Oxboys, aes(Occasion, height)) +
  geom_boxplot()

# Not what we want
ggplot(Oxboys, aes(Occasion, height)) +
  geom_boxplot() +
  geom_line(color = "#3366FF", alpha = 0.5)

ggplot(Oxboys, aes(Occasion, height)) +
  geom_boxplot() +
  geom_line(aes(group = Subject), color = "#3366FF", alpha = 0.5)
```

Matching aes to graphic objects

```{r}
df <- data.frame(x = 1:3, y = 1:3, color = c(1,3,5))

ggplot(df, aes(x,y, color = factor(color))) +
  geom_line(aes(group = 1), size = 2) +
  geom_point(size = 5)

ggplot(df, aes(x, y, color = color)) +
  geom_line(aes(group = 1), size = 2) +
  geom_point(size = 5)

xgrid <- with(df, seq(min(x), max(x), length = 50))
interp <- data.frame(
  x = xgrid,
  y = approx(df$x, df$y, xout = xgrid)$y,
  color = approx(df$x, df$color, xout = xgrid)$y
)
ggplot(interp, aes(x, y, color = color)) +
  geom_line(size = 2) +
  geom_point(data = df, size = 5)

ggplot(mpg, aes(class)) +
  geom_bar()
ggplot(mpg, aes(class, fill = drv)) +
  geom_bar()

ggplot(mpg, aes(class, fill = hwy)) +
  geom_bar()
ggplot(mpg, aes(class, fill = hwy, group = hwy)) +
  geom_bar()
```
