---
title: 'ggplot2 Elegant Graphics: Chapter 5'
author: "Brandon Foltz"
date: "2023-03-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

Discrete x, range: geom_errorbar(), geom_linerange()
Discrete x, range & center: geom_crossbar(), geom_pointrange()
Continuous x, range: geom_ribbon()
Continuous x, range & center: geom_smooth(stat = "identity")

```{r}
y <- c(18,11,16)
df <- data.frame(
  x = 1:3,
  y = y,
  se = c(1.2, 0.5, 1.0)
)

base <- ggplot(df, aes(x, y, ymin = y - se, ymax = y + se))
base + geom_crossbar()
base + geom_pointrange()
base + geom_smooth(stat = "identity")

base + geom_errorbar()
base + geom_linerange()
base + geom_ribbon()
```

Weighting

```{r}
ggplot(midwest, aes(percwhite, percbelowpoverty)) +
  geom_point()

#weight by population
ggplot(midwest, aes(percwhite, percbelowpoverty)) +
  geom_point(aes(size = poptotal / 1e6)) +
  scale_size_area("Population\n(millions)", breaks = c(0.5, 1, 2, 4))
```

```{r}
# unweighted

ggplot(midwest, aes(percwhite, percbelowpoverty)) +
  geom_point() +
  geom_smooth(method = lm, size = 1)

# weighted by population

ggplot(midwest, aes(percwhite, percbelowpoverty)) +
  geom_point(aes(size = poptotal / 1e6)) +
  geom_smooth(aes(weight = poptotal), method = lm, size = 1) +
  scale_size_area(guide = "none")
```

```{r}
ggplot(midwest, aes(percbelowpoverty)) +
  geom_histogram(binwidth = 1) +
  ylab("Counties")

ggplot(midwest, aes(percbelowpoverty)) +
  geom_histogram(aes(weight = poptotal), binwidth = 1) +
  ylab("Population (1000s)")
```

Diamonds data

```{r}
ggplot(diamonds, aes(depth)) +
  geom_histogram()

ggplot(diamonds, aes(depth)) +
  geom_histogram(binwidth = 0.1) +
  xlim(55, 70)
```

```{r}
ggplot(diamonds, aes(depth)) +
  geom_freqpoly(aes(color = cut), binwidth = 0.1, na.rm = TRUE) +
  xlim(58, 68) +
  theme(legend.position = "none")

ggplot(diamonds, aes(depth)) +
  geom_histogram(aes(fill = cut), binwidth = 0.1,  position = "fill", na.rm = TRUE) +
  xlim(58, 68) +
  theme(legend.position = "none")
```

```{r}
ggplot(diamonds, aes(depth)) +
  geom_density(na.rm = TRUE) +
  xlim(58, 68) +
  theme(legend.position = "none")

ggplot(diamonds, aes(depth, fill = cut, color = cut)) +
  geom_density(alpha = 0.2, na.rm = TRUE) +
  xlim(58, 68) +
  theme(legend.position = "none")
```

Boxplots

```{r}
ggplot(diamonds, aes(clarity, depth)) +
  geom_boxplot()

ggplot(diamonds, aes(carat, depth)) +
  geom_boxplot(aes(group = cut_width(carat, 0.1))) +
  xlim(NA, 2.05)
```

```{r}
ggplot(diamonds, aes(clarity, depth)) +
  geom_violin()

ggplot(diamonds, aes(carat, depth)) +
  geom_violin(aes(group = cut_width(carat, 0.1))) +
  xlim(NA, 2.05)
```

Overplotting

```{r}
df <- data.frame(
  x = rnorm(2000),
  y = rnorm(2000)
)

norm <- ggplot(df, aes(x, y)) + xlab(NULL) + ylab(NULL)
norm + geom_point()
norm + geom_point(shape = 1)
norm + geom_point(shape = ".")

norm + geom_point(alpha = 1/3)
norm + geom_point(alpha = 1/10)

norm + geom_bin2d()
norm + geom_bin2d(bins = 10)

norm + geom_hex()
norm + geom_hex(bins = 10)
```

Statistical Summaries

```{r}
ggplot(diamonds,
       aes(color)) +
  geom_bar()

ggplot(diamonds, aes(color, price)) +
  geom_bar(stat = "summary_bin", fun = mean)
```

```{r}
ggplot(diamonds, aes(table, depth)) +
  geom_bin_2d(binwidth = 1, na.rm = TRUE) +
  xlim(50,70) +
  ylim(50,70)

ggplot(diamonds, aes(table, depth, z = price)) +
  geom_raster(binwidth = 1, stat = "summary_2d", fun = mean, na.rm = TRUE) +
  xlim(50, 70) +
  ylim(50, 70)
```

Surfaces

```{r}
ggplot(faithfuld, aes(eruptions, waiting)) +
  geom_contour(aes(z = density, color = ..level..))

ggplot(faithfuld, aes(eruptions, waiting)) +
  geom_raster(aes(fill = density))

small <- faithfuld[seq(1, nrow(faithfuld), by = 10), ]
ggplot(small,
       aes(eruptions, waiting)) +
  geom_point(aes(size = density), alpha = 0.3) +
  scale_size_area()
```

