---
title: 'ggplot2 Elegant Graphics: Chapter 6'
author: "Brandon Foltz"
date: "2023-03-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ozmaps)
library(sf)
```

```{r}
mi_counties <- map_data("county", "michigan")|>
  select(lon = long, lat, group, id = subregion)
head(mi_counties)

ggplot(mi_counties,
       aes(lon, lat)) +
  geom_point(size = .25, show.legend = FALSE) +
  coord_quickmap()

ggplot(mi_counties,
       aes(lon, lat, group = group)) +
  geom_polygon(fill = "white", color = "grey50") +
  coord_quickmap()
```

Simple Features

```{r}
oz_states <- ozmaps::ozmap_states
oz_states

ggplot(oz_states) +
  geom_sf() +
  coord_sf()
```

Layered Maps

```{r}
oz_states <- ozmaps::ozmap_states|>
  filter(NAME != "Other Territories")
oz_votes <- rmapshaper::ms_simplify(ozmaps::abs_ced)

ggplot() +
  geom_sf(data = oz_states, mapping = aes(fill = NAME), show.legend = FALSE) + 
  geom_sf(data = oz_votes, fill = NA) +
  coord_sf()
```

Labelled Maps

```{r}
sydney_map <- ozmaps::abs_ced %>% filter(NAME %in% c(
  "Sydney", "Wentworth", "Warringah", "Kingsford Smith", "Grayndler", "Lowe", 
  "North Sydney", "Barton", "Bradfield", "Banks", "Blaxland", "Reid", 
  "Watson", "Fowler", "Werriwa", "Prospect", "Parramatta", "Bennelong", 
  "Mackellar", "Greenway", "Mitchell", "Chifley", "McMahon"
))

ggplot(sydney_map) +
  geom_sf(aes(fill = NAME), show.legend = FALSE) +
  coord_sf(xlim = c(150.97, 151.3), ylim = c(-33.98, -33.79)) +
  geom_sf_label(aes(label = NAME), label.padding = unit(1, "mm"))
```

Adding other geoms

```{r}
oz_capitals <- tibble::tribble( 
  ~city,           ~lat,     ~lon,
  "Sydney",    -33.8688, 151.2093,  
  "Melbourne", -37.8136, 144.9631, 
  "Brisbane",  -27.4698, 153.0251, 
  "Adelaide",  -34.9285, 138.6007, 
  "Perth",     -31.9505, 115.8605, 
  "Hobart",    -42.8821, 147.3272, 
  "Canberra",  -35.2809, 149.1300, 
  "Darwin",    -12.4634, 130.8456, 
)

ggplot() +
  geom_sf(data = oz_votes) +
  geom_sf(data = oz_states, color = "black", fill = NA) +
  geom_point(data = oz_capitals, mapping = aes(x = lon, y = lat), color = "red") +
  coord_sf()
```

```{r}
ggplot(oz_votes) + geom_sf()
ggplot(oz_votes) + geom_sf() + coord_sf(crs = st_crs(3112))
```

Working with sf data
```{r}
edenmonaro <- ozmaps::abs_ced|>
  filter(NAME == "Eden-Monaro")

p  <- ggplot(edenmonaro) + geom_sf()
p + coord_sf(xlim = c(147.75, 150.25), ylim = c(-37.5, -34.5))
p + coord_sf(xlim = c(150, 150.25), ylim = c(-36.3, -36))

edenmonaro <- edenmonaro|>
  pull(geometry)

st_bbox(edenmonaro)

edenmonaro

st_cast(edenmonaro, "POLYGON")
```
```{r}
dawson <- ozmaps::abs_ced|>
  filter(NAME == "Dawson")|>
  pull(geometry)
dawson

ggplot(dawson) +
  geom_sf() +
  coord_sf()

# Find only the islands

# find mainland
dawson <- st_cast(dawson, "POLYGON")
which.max(st_area(dawson))

# remove mainland to get islands
ggplot(dawson[-69]) +
  geom_sf() +
  coord_sf()
```

Raster Images

```{r}
# list of all file names with time stamp 2020-01-07 21:00 GMT 
# (BOM images are retained for 24 hours, so this will return an
# empty vector if you run this code without editing the time stamp)
files <- bomrang::get_available_imagery() %>%
  stringr::str_subset("202001072100") 

# use curl_download() to obtain a single file, and purrr to 
# vectorise this operation
purrr::walk2(
  .x = paste0("ftp://ftp.bom.gov.au/anon/gen/gms/", files),
  .y = file.path("raster", files),
  .f = ~ download.file(url = .x, destfile = .y)
)
```

