---
title: 'ggplot2 Elegant Graphs: Chapter 16'
author: "Brandon Foltz"
date: "2023-03-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```
```{r}
base <- ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  geom_smooth()

base
base + scale_x_continuous(limits = c(4,6)) #throws away data, affects line
base + coord_cartesian(xlim = c(4,6)) # keeps data, line full data

```
```{r}
ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  geom_smooth()

ggplot(mpg, aes(hwy, displ)) +
  geom_point() +
  geom_smooth()

ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  geom_smooth() +
  coord_flip()
```

Non-linear coordinate systems

```{r}
rect <- data.frame(x = 50, y = 50)
line <- data.frame(x = c(1, 200), y = c(100, 1))
base <- ggplot(mapping = aes(x, y)) + 
  geom_tile(data = rect, aes(width = 50, height = 50)) + 
  geom_line(data = line) + 
  xlab(NULL) + ylab(NULL)
base
base + coord_polar("x")
base + coord_polar("y")
```

```{r}
# Linear model on original scale is poor fit
base <- ggplot(diamonds, aes(carat, price)) + 
  stat_bin2d() + 
  geom_smooth(method = "lm") + 
  xlab(NULL) + 
  ylab(NULL) + 
  theme(legend.position = "none")
base
#> `geom_smooth()` using formula 'y ~ x'

# Better fit on log scale, but harder to interpret
base +
  scale_x_log10() + 
  scale_y_log10()
#> `geom_smooth()` using formula 'y ~ x'

# Fit on log scale, then backtransform to original.
# Highlights lack of expensive diamonds with large carats
pow10 <- scales::exp_trans(10)
base +
  scale_x_log10() + 
  scale_y_log10() + 
  coord_trans(x = pow10, y = pow10)
#> `geom_smooth()` using formula 'y ~ x'
```

